### ISSUE TITLE
Dashboard being served by mnstate.edu not updating past 9 November 2021

### ISSUE THREAD

**Issue by amyrowell** [JuanCab/COVID_DataViz#1]
The version of this GitHub COVID_DataViz at [URL REMOVED] has not been pulling data since 9 November 2021. Is this site no longer being updated or has Release 1.65 not been implemented there?

**Comment by JuanCab** [comment]
That site is not really meant for public consumption, its an internal website for the university community.  The failure happened because of a bad 'git merge' to the John Hopkins data.  I am fixing it now.

There is an issue with pulling IMHE data (hasn't actually been updated on my site since January 2021 due to a format change in their data that I haven't dealt with).

**Comment by amyrowell** [comment]
Thanks for the explanation. Just letting you know that since the university website was presented at the SciPy conference in 2020 a lot of non-university folk probably like to visit it.

**Comment by JuanCab** [comment]
Oh, that makes sense, I bet Matt presented it there as an example of what is possible with Jupiter Notebooks.
